/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package igu;

/**
 *
 * @author sinai
 */
public class EntrarSalir extends javax.swing.JFrame {

    /** Creates new form EntrarSalir */
    public EntrarSalir() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlEstacionamiento1 = new javax.swing.JPanel();
        pnlEstacionamiento2 = new javax.swing.JPanel();
        pnlEstacionamiento3 = new javax.swing.JPanel();
        pnlEstacionamiento3uno = new javax.swing.JPanel();
        pnlE400 = new javax.swing.JPanel();
        pnlE300 = new javax.swing.JPanel();
        pnlE200 = new javax.swing.JPanel();
        pnlE100 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(180, 210, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1180, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnlEstacionamiento1Layout = new javax.swing.GroupLayout(pnlEstacionamiento1);
        pnlEstacionamiento1.setLayout(pnlEstacionamiento1Layout);
        pnlEstacionamiento1Layout.setHorizontalGroup(
            pnlEstacionamiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        pnlEstacionamiento1Layout.setVerticalGroup(
            pnlEstacionamiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        jPanel1.add(pnlEstacionamiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 270, 240));

        javax.swing.GroupLayout pnlEstacionamiento2Layout = new javax.swing.GroupLayout(pnlEstacionamiento2);
        pnlEstacionamiento2.setLayout(pnlEstacionamiento2Layout);
        pnlEstacionamiento2Layout.setHorizontalGroup(
            pnlEstacionamiento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        pnlEstacionamiento2Layout.setVerticalGroup(
            pnlEstacionamiento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel1.add(pnlEstacionamiento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 280, 230));

        javax.swing.GroupLayout pnlEstacionamiento3Layout = new javax.swing.GroupLayout(pnlEstacionamiento3);
        pnlEstacionamiento3.setLayout(pnlEstacionamiento3Layout);
        pnlEstacionamiento3Layout.setHorizontalGroup(
            pnlEstacionamiento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        pnlEstacionamiento3Layout.setVerticalGroup(
            pnlEstacionamiento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jPanel1.add(pnlEstacionamiento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 530, 170));

        javax.swing.GroupLayout pnlEstacionamiento3unoLayout = new javax.swing.GroupLayout(pnlEstacionamiento3uno);
        pnlEstacionamiento3uno.setLayout(pnlEstacionamiento3unoLayout);
        pnlEstacionamiento3unoLayout.setHorizontalGroup(
            pnlEstacionamiento3unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        pnlEstacionamiento3unoLayout.setVerticalGroup(
            pnlEstacionamiento3unoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(pnlEstacionamiento3uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 260, 70));

        javax.swing.GroupLayout pnlE400Layout = new javax.swing.GroupLayout(pnlE400);
        pnlE400.setLayout(pnlE400Layout);
        pnlE400Layout.setHorizontalGroup(
            pnlE400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlE400Layout.setVerticalGroup(
            pnlE400Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel1.add(pnlE400, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, 210));

        javax.swing.GroupLayout pnlE300Layout = new javax.swing.GroupLayout(pnlE300);
        pnlE300.setLayout(pnlE300Layout);
        pnlE300Layout.setHorizontalGroup(
            pnlE300Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlE300Layout.setVerticalGroup(
            pnlE300Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(pnlE300, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, 80));

        javax.swing.GroupLayout pnlE200Layout = new javax.swing.GroupLayout(pnlE200);
        pnlE200.setLayout(pnlE200Layout);
        pnlE200Layout.setHorizontalGroup(
            pnlE200Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlE200Layout.setVerticalGroup(
            pnlE200Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(pnlE200, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, 80));

        javax.swing.GroupLayout pnlE100Layout = new javax.swing.GroupLayout(pnlE100);
        pnlE100.setLayout(pnlE100Layout);
        pnlE100Layout.setHorizontalGroup(
            pnlE100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlE100Layout.setVerticalGroup(
            pnlE100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(pnlE100, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlE100;
    private javax.swing.JPanel pnlE200;
    private javax.swing.JPanel pnlE300;
    private javax.swing.JPanel pnlE400;
    private javax.swing.JPanel pnlEstacionamiento1;
    private javax.swing.JPanel pnlEstacionamiento2;
    private javax.swing.JPanel pnlEstacionamiento3;
    private javax.swing.JPanel pnlEstacionamiento3uno;
    // End of variables declaration//GEN-END:variables

}
